# Generated by Django 3.1.3 on 2020-12-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0003_auto_20201204_2328'),
        ('account', '0002_auto_20201127_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='offers',
            field=models.ManyToManyField(blank=True, related_name='offers', to='main_system.Offer'),
        ),
    ]
