# Generated by Django 3.1.3 on 2020-11-23 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201123_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='locals',
            new_name='rooms',
        ),
    ]
