# Generated by Django 3.1.3 on 2020-11-09 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catering',
            name='basic_offer',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='website',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='catering',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_system.catering'),
        ),
        migrations.AlterField(
            model_name='otheroffer',
            name='basic_offer',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='air_conditioned',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='type_of_parquet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
