# Generated by Django 3.1.3 on 2020-11-27 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='offer_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='offer',
            name='catering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_system.catering'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_system.local'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='other_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_system.otherprovider'),
        ),
    ]
