# Generated by Django 3.1.3 on 2020-12-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0002_auto_20201127_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='voivodeship',
        ),
        migrations.AlterField(
            model_name='contact',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
